name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      # Uncomment if you want to specify a certain
      # Node version. Otherwise the Node version installed
      # on the GitHub VM will be used. For more details
      # see: https://github.com/actions/virtual-environments
      # - name: Setup Node.js environment
      #   uses: actions/setup-node@v2.1.4
      #   with:
      #     node-version: '15.7.0'

      - name: Install dependencies
        run: npm ci

      - name: Fix Vulnerabilities
        run: npm audit fix --force

      - name: Build the website
        run: npx @11ty/eleventy

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: pixie-ftp.porkbun.com
          username: orionlw.me
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: _site/
          server-dir: /
